name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 79.143.94.91
          port: 2222
          username: kevin
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd /var/www/html/red-social; git stash; git pull; git stash pop; npm run build;
          php artisan optimize; sudo service php8.2-fpm reload"
